#pragma once
#include <map>

enum EGOAPSymbol
{
	// EGOAPSYMBOL_

	// DEFAULT
	EGOAPSYMBOL_DEFAULT = 0,

	// Resource on AI
	EGOAPSYMBOL_HAVE_WOOD,
	EGOAPSYMBOL_HAVE_STONE,
	EGOAPSYMBOL_HAVE_IRON,
	EGOAPSYMBOL_HAVE_MEAT,
	EGOAPSYMBOL_HAVE_FOOD,

	// Resource in stockpile
	EGOAPSYMBOL_AVAILABLE_WOOD,
	EGOAPSYMBOL_AVAILABLE_STONE,
	EGOAPSYMBOL_AVAILABLE_IRON,
	EGOAPSYMBOL_AVAILABLE_MEAT,
	EGOAPSYMBOL_AVAILABLE_FOOD,

	// Tool on AI
	EGOAPSYMBOL_HAVE_TOOL,
	EGOAPSYMBOL_HAVE_WEAPON,

	// Tool at forge
	EGOAPSYMBOL_AVAILABLE_TOOL,
	EGOAPSYMBOL_AVAILABLE_WEAPON,

	// Weapon type
	EGOAPSYMBOL_WEAPON_IS_RANGED,

	// Target exists
	EGOAPSYMBOL_TREE_EXISTS,
	EGOAPSYMBOL_ROCK_EXISTS,
	EGOAPSYMBOL_ENEMY_EXISTS,

	// Target in Range
	EGOAPSYMBOL_TARGET_IN_RANGE,

	// AI State
	EGOAPSYMBOL_HUNGRY,

	// Object Exists
	EGOAPSYMBOL_EXISTS_FIRE,

	// Object Active
	EGOAPSYMBOL_ACTIVE_FIRE,

	// TOTAL SYMBOLS
	EGOAPSYMBOL_TOTAL
};

using SymbolMap = std::map<EGOAPSymbol, bool>;
