#pragma once

enum EResourceType
{
	//ERESOURCETYPE_

	ERESOURCETYPE_WOOD = 0,
	ERESOURCETYPE_STONE,
	ERESOURCETYPE_IRON,
	ERESOURCETYPE_FOOD,
	ERESOURCETYPE_MEAT,
	ERESOURCETYPE_VEG,

	ERESOURCETYPE_TOTAL
};